#!/bin/sh
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABL_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

export PATH=/home/jordan/.nix-profile/bin:/home/jordan/.local/bin:$PATH

# export TUIGREET_THEME='border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red'



exec sway "$@"
